-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 19:20:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema flowergarden
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flowergarden` DEFAULT CHARACTER SET utf8 ;
USE `flowergarden` ;

-- -----------------------------------------------------
-- Table `flowergarden`.`flower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flowergarden`.`flower` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `cost` DOUBLE NOT NULL,
  `stemLength` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `flowergarden`.`livingFlower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flowergarden`.`livingFlower` (
  `id` INT NOT NULL,
  `cuttingDate` DATETIME NOT NULL,
  `lifeTime` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_baseFlowerId`
    FOREIGN KEY (`id`)
    REFERENCES `flowergarden`.`flower` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `flowergarden`.`multipleFlowers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flowergarden`.`multipleFlowers` (
  `id` INT NOT NULL,
  `flowersOnStemAmount` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_livingFlowerId`
    FOREIGN KEY (`id`)
    REFERENCES `flowergarden`.`livingFlower` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `flowergarden`.`rose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flowergarden`.`rose` (
  `id` INT NOT NULL,
  `isSpiked` TINYINT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_multipleFlowersId`
    FOREIGN KEY (`id`)
    REFERENCES `flowergarden`.`multipleFlowers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `flowergarden`.`tulip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flowergarden`.`tulip` (
  `id` INT NOT NULL,
  `rarityCoef` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_livingFlowerId_tulip`
    FOREIGN KEY (`id`)
    REFERENCES `flowergarden`.`livingFlower` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flowergarden`.`decoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flowergarden`.`decoration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `cost` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
